#!/usr/bin/env python3
"""Generate the deterministic CrazyDashboard documentation index."""

# EN: Generate a stable index from document metadata without third-party dependencies.
# ES: Genera un índice estable a partir de metadatos sin dependencias de terceros.
# 中文：只使用标准库，根据文档元数据生成稳定的文档索引。

from __future__ import annotations

import argparse
import sys
from pathlib import Path


DOCS_DIR = Path(__file__).resolve().parent.parent / "docs"
INDEX_PATH = DOCS_DIR / "README.md"


def parse_front_matter(path: Path) -> dict[str, object]:
    """Parse the deliberately small YAML subset used by the repository."""

    # EN: Keep parsing intentionally small so the governance check has no package dependency.
    # ES: Mantén el análisis deliberadamente pequeño para no depender de paquetes.
    # 中文：只解析仓库约定的简单 YAML 子集，避免引入第三方包。
    lines = path.read_text(encoding="utf-8").splitlines()
    if not lines or lines[0].strip() != "---":
        return {}

    end = next((index for index, line in enumerate(lines[1:], start=1) if line.strip() == "---"), None)
    if end is None:
        return {}

    result: dict[str, object] = {}
    active_list_key: str | None = None
    for line in lines[1:end]:
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        stripped = line.strip()
        if stripped.startswith("-") and active_list_key:
            result.setdefault(active_list_key, [])
            values = result[active_list_key]
            if isinstance(values, list):
                values.append(stripped[1:].strip())
            continue
        if ":" not in line:
            active_list_key = None
            continue
        key, raw_value = line.split(":", 1)
        key = key.strip()
        value = raw_value.strip()
        if not value:
            result[key] = []
            active_list_key = key
            continue
        active_list_key = None
        if value in {"true", "false"}:
            result[key] = value == "true"
        else:
            result[key] = value.strip('"\'')
    return result


def documents() -> list[tuple[Path, dict[str, object]]]:
    entries: list[tuple[Path, dict[str, object]]] = []
    for path in sorted(DOCS_DIR.rglob("*.md")):
        if path == INDEX_PATH:
            continue
        entries.append((path, parse_front_matter(path)))
    return entries


def render() -> str:
    entries = documents()
    lines = [
        "<!-- Generated by Scripts/generate_docs_index.py; do not edit manually. -->",
        "# CrazyDashboard 文档索引",
        "",
        "从这里进入当前产品、计划、架构、协议、研究、历史和归档文档。规则详见 [`DOCUMENTATION_POLICY.md`](DOCUMENTATION_POLICY.md)。",
        "",
        "## 推荐入口",
        "",
        "- [`product/APP_FEATURE_BLUEPRINT.md`](product/APP_FEATURE_BLUEPRINT.md)：当前产品功能唯一事实源",
        "- [`planning/ACTIVE_WORK.md`](planning/ACTIVE_WORK.md)：当前未完成工作与验收门",
        "- [`planning/BACKLOG.md`](planning/BACKLOG.md)：未排期候选与技术债",
        "- [`architecture/`](architecture/)：稳定系统边界与数据流",
        "- [`protocols/`](protocols/)：XP400 BLE、YMOBD/Jieli 协议参考",
        "- [`research/`](research/)：设备、抓包和协议研究日志",
        "- [`history/`](history/)：年度 Build 结果",
        "",
        "## 全部项目级文档",
        "",
        "| 文档 | 类型 | 状态 | Canonical | 最后复核 |",
        "| --- | --- | --- | --- | --- |",
    ]
    for path, metadata in sorted(entries, key=lambda item: (str(item[1].get("type", "")), str(item[1].get("title", "")), str(item[0]))):
        relative = path.relative_to(DOCS_DIR).as_posix()
        title = str(metadata.get("title", path.stem)).replace("|", "\\|")
        doc_type = str(metadata.get("type", "missing"))
        status = str(metadata.get("status", "missing"))
        canonical = "是" if metadata.get("canonical") is True else "否"
        reviewed = str(metadata.get("last_reviewed", ""))
        lines.append(f"| [`{relative}`]({relative}) | {doc_type} | {status} | {canonical} | {reviewed} |")

    lines.extend(
        [
            "",
            "> `PTSpeedTests/ReplayFixtures/README.md` 是测试夹具旁的局部说明，保留在代码目录中，不纳入本项目级索引。",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the CrazyDashboard documentation index")
    parser.add_argument("--check", action="store_true", help="fail when the checked-in index is stale")
    args = parser.parse_args()

    rendered = render()
    if args.check:
        if not INDEX_PATH.exists() or INDEX_PATH.read_text(encoding="utf-8") != rendered:
            print("documentation index is stale; run Scripts/generate_docs_index.py", file=sys.stderr)
            return 1
        print("documentation index is up to date")
        return 0

    INDEX_PATH.write_text(rendered, encoding="utf-8")
    print(f"generated {INDEX_PATH.relative_to(INDEX_PATH.parent.parent)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

